# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.12.1
        with:
          # The tag name to be associated with the GitHub release that's created or updated.
          # This will override any `tag-template` specified in your `release-drafter.yml` if defined.
          # tag: # optional

          # The version to be associated with the GitHub release that's created or updated.
          # This  will override any version calculated by the release-drafter.
          # version: # optional

          # A boolean indicating whether the release being created or updated should be immediately published.
          publish: true

      - name: Release-Notes-Preview
        uses: snyk/release-notes-preview@v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        
      - name: Semantic Releaser
        uses: brpaz/action-semantic-release@v1
        with:
          # Specifies a list of extra plugins to install
          #install_plugins: # optional
          # Run semantic release in dry-run mode
          dry_run: false
